server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8
    max-threads: 300
    min-spare-threads: 30
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: chen2908
      url: jdbc:mysql://localhost:3306/tp_mymusic?characterEncoding=utf-8&useSSL=false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: true
  redis:
    database: 0
    host: 192.168.234.135
    port: 6379
    password: chen2908
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
mymusic:
  jwt:
    enabled: true
    secret: fjkfaf;afa
    expiration: 36000000
    header: JWTHeaderName
    userParamName: username
    pwdParamName: password
    useDefaultController: true
    corsAllowedOrigins:
      - http://localhost:8080
      - http://127.0.0.1:8080
      - http://localhost:8088
      - http://localhost:8083
    corsAllowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
    devOpeningURI:
    permitAllURI:
      - /songList/getSongListByPage
      - /songList/getSongListHot
      - /songList/getStyleByPage
      - /songList/update
      - /song/getSongOfSingerId
      - /song/getSongOfSongListId
      - /song/SongOfQuerySongNameOrSingerName
      - /singer/getSingerByPage
      - /singer/getSingerBySingerName
      - /singer/getSingerBySex
      - /singer/getSingerHot
      - /sysuser/add
      - /user/login/status
      - /comment/getCommentByPage
      - /rank
      - /admin/login/status
      - /monitor/server
      - /test/gethost

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.mymusic.domain

# 上传七牛云的文件密钥
file:
  Access_Key:  Ud6hdmRtoRw2A0sO8V2j8MAX3E7SM-VvXdhHHX_g
  Secret_Key:  =SP9eu88pWSAvUjseKuyEPEbCL8vAY04a_vhJ3NBF

# 配置腾讯对象存储的密钥信息
cos:
  hostName: https://music-1305663279.cos.ap-nanjing.myqcloud.com
  bucketName: music-1305663279
  region:  ap-nanjing
  secretId:  AKIDX3SaV9wlgO4XjhNrBGA5rdCxUmqflBaP
  secretKey: oNhNjusjPs8LfldFjNq6ArTu8DE2asoX

# 日志的配置信息
logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/code/project/mymusic/music-server/log


