package com.mymusic.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/*歌单的实体类*/
@Data
@AllArgsConstructor
@NoArgsConstructor
public class SongList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_list.id
     *
     * @mbg.generated Wed Dec 16 13:24:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_list.title
     *
     * @mbg.generated Wed Dec 16 13:24:13 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_list.pic
     *
     * @mbg.generated Wed Dec 16 13:24:13 CST 2020
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_list.style
     *
     * @mbg.generated Wed Dec 16 13:24:13 CST 2020
     */
    private String style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_list.introduction
     *
     * @mbg.generated Wed Dec 16 13:24:13 CST 2020
     */
    private String introduction;
}